apiVersion: apps/v1
kind: Deployment
metadata:
  name: rock-paper-scissors
  namespace: rock-paper-scissors
  labels:
    app: rock-paper-scissors
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rock-paper-scissors
  template:
    metadata:
      labels:
        app: rock-paper-scissors
    spec:
      containers:
      - name: rock-paper-scissors
        image: rock-paper-scissors:latest
        ports:
        - containerPort: 5000